set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

bind r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"

set-window-option -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g set-clipboard on
bind-key -T copy-mode-vi v send-keys -X begin-selection
# copy tmux to clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
# paste clipboard within tmux
bind C-v run "wl-paste -n | tmux load-buffer - && tmux paste-buffer"

# tokyo-night
# status bar background/foreground
set -g status-style "fg=#7aa2f7,bg=#16161e"
# active window in the window list
setw -g window-status-current-format "#[fg=#16161e,bg=#3b4261,nobold,nounderscore,noitalics]#[fg=#7aa2f7,bg=#3b4261,bold] #I  #W #F #[fg=#3b4261,bg=#16161e,nobold,nounderscore,noitalics]"
# inactive windows
setw -g window-status-style "NONE,fg=#a9b1d6,bg=#16161e"
# pane borders — active vs inactive
set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"
# command/message line
set -g message-style "fg=#7aa2f7,bg=#3b4261"
